import uuid
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from app.api.deps import UPLOAD_DIR, _last_st
from app.api.schemas import (
    ChatRequest,
    ChatResponse,
    GenerateModuleRequest,
    GenerateModuleResponse,
    ValidateRequest,
    ValidateResponse,
)

router = APIRouter(tags=["Agent"])


@router.post("/chat", response_model=ChatResponse, summary="ReAct-агент: генерация ST-кода на естественном языке")
async def chat(body: ChatRequest):
    from app.agents.react_agent import run_agent

    sid = body.session_id or str(uuid.uuid4())
    result = await run_agent(body.message, session_id=sid)
    return ChatResponse(**result)


@router.post(
    "/generate_module",
    response_model=GenerateModuleResponse,
    summary="Генерация ST-модуля для Эльбрус/Байкал по таблице сигналов",
)
async def generate_module(body: GenerateModuleRequest):
    from app.tools.matiec_client import compile_st
    from app.tools.signal_parser import parse_signal_table, signals_to_scale_body, signals_to_st_var

    sid = body.session_id or str(uuid.uuid4())

    if body.signals_path and Path(body.signals_path).exists():
        signals = parse_signal_table(body.signals_path)
        var_section = signals_to_st_var(signals, body.controller)
        scale_body = signals_to_scale_body(signals)
    else:
        var_section = "VAR\n    (* No signals loaded — upload CSV via /upload_signals *)\nEND_VAR"
        scale_body = "(* Add scaling logic here *)"

    code = f"""(* ================================================================ *)
(* MODULE: {body.module_name}                                         *)
(* CONTROLLER: {body.controller.upper()} (Elbrus-2C3)                *)
(* GENERATED BY: Talos Harness v2.0                                   *)
(* IEC 61131-3 Structured Text                                        *)
(* ================================================================ *)

PROGRAM {body.module_name}
{var_section}

{scale_body}

(* ── Control logic ─────────────────────────────────────────────── *)
(* Add your control logic here                                        *)

(* VERIFY: Check all AI scaling, DO outputs and alarm conditions *)
END_PROGRAM
"""
    mat = await compile_st(code, sid)

    out_path = UPLOAD_DIR / f"module_{sid}.st"
    out_path.write_text(code, encoding="utf-8")
    _last_st[sid] = str(out_path)

    return GenerateModuleResponse(
        session_id=sid,
        controller=body.controller,
        module_name=body.module_name,
        code=code,
        matiec_ok=mat.ok,
        matiec_errors=mat.errors,
        download_url=f"/module/download?session_id={sid}",
    )


@router.get("/module/download", summary="Скачать сгенерированный .st файл")
async def download_module(session_id: str = Query(...)):
    path = _last_st.get(session_id)
    if not path or not Path(path).exists():
        raise HTTPException(404, "Module not found. Run /generate_module first.")
    return FileResponse(path, filename="module.st", media_type="text/plain")


@router.post("/validate", response_model=ValidateResponse, summary="Валидация ST-кода через MatIEC (iec2c)")
async def validate_code(body: ValidateRequest):
    from app.tools.matiec_client import compile_st

    r = await compile_st(body.code, body.task_id)
    return ValidateResponse(
        ok=r.ok,
        compilation_rate=r.compilation_rate,
        errors=r.errors,
        warnings=r.warnings,
    )
